Create Database SistemaPacientes;

USE SistemaPacientes;
GO

CREATE TABLE Pacientes (
    id_paciente INT PRIMARY KEY IDENTITY(1,1),
    nomb_pac NVARCHAR(50),
    apel_pac NVARCHAR(50),
    edad_pac INT,
    CIE_10 NVARCHAR(50)
);
GO

INSERT INTO Pacientes (nomb_pac, apel_pac, edad_pac, CIE_10) VALUES 
('Juan', 'Perez', 12, 'COVID-19'),
('Maria', 'Gomez', 25, 'Gripe'),
('Carlos', 'Lopez', 45, 'COVID-19'),
('Ana', 'Diaz', 65, 'Asma'),
('Luis', 'Torres', 16, 'COVID-19'),
('Elena', 'Ramirez', 35, 'Neumonia'),
('Pedro', 'Cruz', 72, 'COVID-19'),
('Sofia', 'Fernandez', 8, 'Gripe'),
('Miguel', 'Ruiz', 50, 'COVID-19'),
('Lucia', 'Morales', 21, 'Migraña'),
('Jorge', 'Herrera', 15, 'COVID-19'),
('Camila', 'Castro', 33, 'Alergia'),
('Mateo', 'Vargas', 55, 'COVID-19'),
('Valeria', 'Rios', 41, 'Bronquitis'),
('Diego', 'Navarro', 68, 'COVID-19'),
('Martina', 'Silva', 10, 'COVID-19'),
('Santiago', 'Mendoza', 19, 'Amigdalitis'),
('Isabella', 'Flores', 47, 'COVID-19'),
('Sebastian', 'Rojas', 62, 'Hipertension'),
('Daniela', 'Medina', 5, 'COVID-19'),
('Andres', 'Castillo', 28, 'Gripe'),
('Valentina', 'Guzman', 39, 'COVID-19'),
('David', 'Ortiz', 14, 'Asma'),
('Paula', 'Jimenez', 53, 'COVID-19'),
('Alejandro', 'Soto', 77, 'Diabetes'),
('Mariana', 'Alvarez', 11, 'COVID-19'),
('Fernando', 'Romero', 22, 'Gripe'),
('Victoria', 'Cordova', 44, 'COVID-19'),
('Joaquin', 'Suarez', 60, 'Neumonia'),
('Gabriela', 'Aguilar', 17, 'COVID-19'),
('Ricardo', 'Paredes', 31, 'Alergia'),
('Antonella', 'Salazar', 80, 'COVID-19'),
('Hugo', 'Vega', 6, 'Gripe'),
('Emilia', 'Maldonado', 26, 'COVID-19'),
('Oscar', 'Ponce', 49, 'Gastritis'),
('Catalina', 'Reyes', 13, 'COVID-19'),
('Javier', 'Campos', 36, 'Asma'),
('Renata', 'Ramos', 64, 'COVID-19'),
('Martin', 'Delgado', 2, 'Gripe'),
('Julieta', 'Leon', 29, 'COVID-19'),
('Emilio', 'Herrera', 58, 'Bronquitis'),
('Samantha', 'Chavez', 18, 'COVID-19'),
('Rafael', 'Ibanez', 70, 'Hipertension'),
('Mia', 'Cabrera', 9, 'COVID-19'),
('Francisco', 'Espinoza', 24, 'Gripe'),
('Zoe', 'Cortes', 42, 'COVID-19'),
('Manuel', 'Pena', 66, 'Diabetes'),
('Amanda', 'Molina', 15, 'COVID-19'),
('Eduardo', 'Aguirre', 34, 'Neumonia'),
('Luciana', 'Cardenas', 51, 'COVID-19'),
('Roberto', 'Serrano', 7, 'Asma'),
('Carolina', 'Rios', 27, 'COVID-19'),
('Arturo', 'Vera', 48, 'Alergia'),
('Alicia', 'Valdez', 69, 'COVID-19'),
('Hector', 'Acosta', 12, 'Gripe'),
('Bianca', 'Galvan', 32, 'COVID-19'),
('Mario', 'Miranda', 57, 'Gastritis'),
('Clara', 'Pacheco', 75, 'COVID-19'),
('Ignacio', 'Lara', 4, 'Neumonia'),
('Flavia', 'Guerra', 20, 'COVID-19'),
('Simon', 'Fuentes', 46, 'Gripe'),
('Jimena', 'Rivas', 63, 'COVID-19'),
('Cristian', 'Montes', 16, 'Asma'),
('Ximena', 'Sosa', 37, 'COVID-19'),
('Gonzalo', 'Escobar', 54, 'Bronquitis'),
('Lola', 'Benitez', 82, 'COVID-19'),
('Raul', 'Bustos', 11, 'Gripe'),
('Andrea', 'Salinas', 23, 'COVID-19'),
('Felipe', 'Carrillo', 43, 'Amigdalitis'),
('Rosa', 'Navarrete', 61, 'COVID-19'),
('Esteban', 'Pino', 8, 'Asma'),
('Angela', 'Tapia', 30, 'COVID-19'),
('Julio', 'Arce', 56, 'Neumonia'),
('Marta', 'Luna', 71, 'COVID-19'),
('Marcos', 'Orozco', 14, 'Alergia'),
('Diana', 'Villanueva', 38, 'COVID-19'),
('Pablo', 'Zuniga', 59, 'Gripe'),
('Teresa', 'Franco', 79, 'COVID-19'),
('Cesar', 'Bravo', 5, 'Bronquitis'),
('Natalia', 'Moya', 25, 'COVID-19'),
('Ivan', 'Arriagada', 40, 'Asma'),
('Silvia', 'Cornejo', 67, 'COVID-19'),
('Rodrigo', 'Garrido', 17, 'Gripe'),
('Beatriz', 'Macias', 35, 'COVID-19'),
('Alvaro', 'Escudero', 52, 'Hipertension'),
('Carmen', 'Urrutia', 74, 'COVID-19'),
('Tomas', 'Vidal', 10, 'Alergia'),
('Lorena', 'Salas', 28, 'COVID-19'),
('Victor', 'Zamorano', 45, 'Neumonia'),
('Gloria', 'Paredes', 65, 'COVID-19'),
('Bruno', 'Santibanez', 3, 'Gripe'),
('Raquel', 'Poblete', 22, 'COVID-19'),
('Patricio', 'Figueroa', 41, 'Gastritis'),
('Ines', 'Vergara', 68, 'COVID-19'),
('Gerardo', 'Contreras', 15, 'Asma'),
('Monica', 'Vallejos', 33, 'COVID-19'),
('Gustavo', 'Araya', 50, 'Gripe'),
('Elsa', 'Caceres', 76, 'COVID-19'),
('Ruben', 'Leal', 13, 'Amigdalitis'),
('Josefina', 'Soto', 29, 'COVID-19');
GO