-- Crear la base de datos
CREATE DATABASE NEGOCIO
GO

-- Usar la base de datos
USE NEGOCIO
GO

-- Crear la tabla PRODUCTOS
CREATE TABLE PRODUCTOS
(
    CODIGO INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    MARCA VARCHAR(50),
    PRECIO FLOAT
)
GO

-- crear la tabla CLIENTES
CREATE TABLE CLIENTES
(
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(50)
)
GO

-- Crear la tabla VENTAS
CREATE TABLE VENTAS
(
    ID INT PRIMARY KEY,
    PRODUCTO VARCHAR(50),
    CANTIDAD INT,
    TOTAL FLOAT
)
GO

-- Ver registros de la tabla
SELECT * FROM PRODUCTOS
SELECT * FROM CLIENTES
SELECT * FROM VENTAS
GO